spring:
  datasource:
    first:
      url: jdbc:postgresql://localhost:5432/first_module
      username: postgres
      password: postgres
    second:
      url: jdbc:postgresql://localhost:5432/second_module
      username: postgres
      password: postgres